import { configureStore } from '@reduxjs/toolkit';
import { todosApi } from './todosApi';

export const store = configureStore({
  reducer: {
    // Here there will be 'slices' of the app state
    // RTK Query automatically adds its reducer by a key mentioned in the API slice
    [todosApi.reducerPath]: todosApi.reducer,
    // If you have other parts of state,
    // they will be added here:
    // auth: authReducer,
    // settings: settingsReducer,
  },
  // Add middleware generated by RTK Query to handle caching, invalidation etc.
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(todosApi.middleware), // .concat(anotherCustomMiddleware) And so on
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
